USE CENTRAL_ADMIN;
INSERT INTO GAMES (GAME_NAME, GAME_TYPE, VERSION, SUPPLIER_ID, GAME_GROUP, GAME_SUB_GROUP, GAME_STATUS, ESTIMATED_DEV_COST, ESTIMATED_TESTING_COST, EXPECTED_MARGIN, 
RANGE_MARGIN, GAME_RELEASE_DATE, HTML5, FLASH, DESKTOP, MOBILE, MINI_GAME) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

/*USE central_admin;
INSERT INTO GAME(GAME_NAME, GAME_TYPE, VERSION, SUPPLIER_ID, GAME_GROUP, GAME_SUB_GROUP, GAME_STATUS, ESTIMATED_DEV_COST, ESTIMATED_TESTING_COST, EXPECTED_MARGIN, 
			RANGE_MARGIN, GAME_RELEASE_DATE, HTML5, FLASH, DESKTOP, MOBILE, MINI_GAME) 
VALUES('Baccarat', 'Casino', 'Version3', 118118, 'Not Sure', 'Not Sure','Not Live', 2000, 1000, 200, 100, '2016-10-23', true, true, true, true, false);  */  